// front_end-frameworks/vue/src/components/ui/Brand.vue
<script setup>
import { BrainCircuit } from "lucide-vue-next";

defineProps({
    name: {
        type: String,
        default: "Agentic AI",
    },
    href: {
        type: String,
        default: "#hero-section",
    },
});
</script>

<template>
  <a
    :href="href"
    class="flex items-center gap-2"
  >
    <span class="rounded-lg bg-violet-500 p-2 text-slate-50">
      <BrainCircuit :size="14" />
    </span>
    <span class="text-slate-50">{{ name }}</span>
  </a>
</template>

// front_end-frameworks/react/src/components/ui/Brand.jsx
import { BrainCircuit } from "lucide-react";

function Brand({ name = "Agentic AI", href = "#hero-section", className = ""}) {
    return (
        <a href={href} className={`flex items-center gap-2 ${className}`}>
            <div className="rounded-lg bg-violet-500 p-2 text-slate-50">
                <BrainCircuit size={14} />
            </div>

            <span className="text-slate-50">
                {name}
            </span>
        </a>
    );
}

export default Brand;
