// front_end-frameworks/svelte/src/components/ui/Brand.svelte
<script>
    import { BrainCircuit } from "@lucide/svelte";

    let {
        name = "Agentic AI",
        href = "#hero-section",
        class: className = "",
    } = $props();
</script>

<a {href} class={`flex items-center gap-2 ${className}`}>
    <span class="rounded-lg bg-violet-500 p-2 text-slate-50">
        <BrainCircuit aria-hidden="true" size={14} />
    </span>

    <span class="text-slate-50">{name}</span>
</a>

// front_end-frameworks/react/src/components/ui/Brand.jsx
import { BrainCircuit } from "lucide-react";

function Brand({ name = "Agentic AI", href = "#hero-section", className = ""}) {
    return (
        <a href={href} className={`flex items-center gap-2 ${className}`}>
            <div className="rounded-lg bg-violet-500 p-2 text-slate-50">
                <BrainCircuit size={14} />
            </div>

            <span className="text-slate-50">
                {name}
            </span>
        </a>
    );
}

export default Brand;
