// front_end-frameworks/svelte/src/components/sections/Insights.svelte
<script>
    import { onMount } from "svelte";
    import InsightCard from "../cards/InsightCard.svelte";
    import SectionBadge from "../ui/SectionBadge.svelte";
    import SectionTitle from "../ui/SectionTitle.svelte";
    import { getInsights } from "../../services/insightsService.js";

    let insights = $state([]);
    let error = $state("");

    onMount(async () => {
        try {
            error = "";
            insights = await getInsights();
        } catch {
            error = "Unable to load insights.";
        }
    });
</script>

<section id="insights-section" class="bg-black">
    <div class="mx-auto flex max-w-6xl flex-col items-center px-6 py-24 text-center">
        <SectionBadge text="Insights" class="mb-4" />
        <SectionTitle title="Explore Agentic AI" highlight="Through real-world scenes" />

        <div class="mt-6 min-h-6" aria-live="polite">
            {#if error}
                <p role="alert" class="text-sm text-red-400">{error}</p>
            {/if}
        </div>

        <div class="mt-6 grid w-full gap-8 md:grid-cols-2 lg:grid-cols-3">
            {#each insights as insight, index (insight.title)}
                <InsightCard {...insight} {index} />
            {/each}
        </div>
    </div>
</section>

// front_end-frameworks/react/src/components/sections/Insights.jsx
import { useEffect, useState } from "react";
import InsightCard from "../cards/InsightCard.jsx";
import { getInsights } from "../../services/insightsService.js";
import SectionBadge from "../ui/SectionBadge.jsx";
import SectionTitle from "../ui/SectionTitle.jsx";

function Insights() {
    const [insights, setInsights] = useState([]);
    const [error, setError] = useState("");

    useEffect(() => {
        const loadInsights = async () => {
            try {
                setError("");
                const data = await getInsights();
                setInsights(data);
            }
            catch {
                setError("Unable to load insights.");
            }
        };
        loadInsights();
    },
    []);

    return (
        <section id="insights-section" className="bg-black">
            <div className="max-w-6xl mx-auto px-6 flex flex-col items-center py-24 text-center">
        

                <SectionBadge text="Insights" className="mb-4"/>

                <SectionTitle title="Explore Agentic AI" highlight="Through real-world scenes"/>

                <div className="mt-6 min-h-6" aria-live="polite">
                    {error && (
                        <p role="alert" className="text-sm text-red-400">
                            {error}
                        </p>
                    )}
                </div>

                <div className="mt-6 grid w-full gap-8 md:grid-cols-2 lg:grid-cols-3">
                    {insights.map((insight, index) => (
                        <InsightCard
                            key={insight.title}
                            category={insight.category}
                            title={insight.title}
                            description={insight.description}
                            image={insight.image}
                            index={index}
                        />
                    ))}
                </div>
            </div>
        </section>
    );
}

export default Insights;
