// front_end-frameworks/vue/src/components/layout/Header.vue
<script setup>
import Brand from "../ui/Brand.vue";
import Button from "../ui/Button.vue";
</script>

<template>
  <header class="fixed top-0 z-50 w-full bg-slate-950 text-slate-50">
    <div class="mx-auto flex max-w-6xl items-center justify-between px-6 py-3">
      <Brand />
      <div class="ml-auto flex items-center gap-4">
        <nav
          aria-label="Main navigation"
          class="hidden md:block"
        >
          <ul class="flex gap-4">
            <li>
              <a
                class="text-sm text-slate-500 hover:text-slate-50"
                href="#about-section"
              >About</a>
            </li>
            <li>
              <a
                class="text-sm text-slate-500 hover:text-slate-50"
                href="#features-section"
              >Features</a>
            </li>
            <li>
              <a
                class="text-sm text-slate-500 hover:text-slate-50"
                href="#insights-section"
              >Insights</a>
            </li>
            <li>
              <a
                class="text-sm text-slate-500 hover:text-slate-50"
                href="#contact-section"
              >Contact</a>
            </li>
          </ul>
        </nav>
        <Button
          href="https://www.holbertonschool.fr/rejoindre-lhippocamp"
          target="_blank"
          rel="noopener noreferrer"
          class="text-sm"
        >
          Enroll now
        </Button>
      </div>
    </div>
  </header>
</template>

// front_end-frameworks/react/src/components/Header.jsx
import { BrainCircuit } from "lucide-react";


function Header() {
  return (

    <header className="fixed top-0 z-50 w-full bg-slate-950 text-white">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-3">
    
            <a
            href="#home-section"
            className="flex items-center gap-2"
            >
                <div className="rounded-lg bg-violet-500 p-2">
                    <BrainCircuit size={14} />
                </div>
                <span className="text-slate-50 font-bold"> 
                    Agentic AI
                </span>
            </a>
            <div className="ml-auto flex items-center gap-4"> {/* ml-auto pousse vers la droit margin left marge a gauche  */}
            <nav aria-label="Main navigation" className="hidden md:block">
                <ul className="flex gap-4">
                    <li>
                        <a
                            className="font-bold text-slate-500 hover:text-white text-sm"
                            href="#about-section"
                        >
                            About
                        </a>
                    </li>

                    <li>
                        <a
                            className="font-bold text-slate-500 hover:text-white text-sm"
                            href="#features-section"
                        >
                            Features
                        </a>
                    </li>

                    <li>
                        <a
                            className="font-bold text-slate-500 hover:text-white text-sm"
                            href="#insights-section"
                        >
                            Insights
                        </a>
                    </li>

                    <li>
                        <a
                            className="font-bold text-slate-500 hover:text-white text-sm"
                            href="#contact-section"
                        >
                            Contact
                        </a>
                    </li>
                </ul>
            </nav>
                <button
                    type="button"
                    className="px-4 py-2 font-semibold rounded-md bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40 text-sm"
                >
                    Enroll now
                </button>
            </div>
        </div>
    </header>
  );
}

export default Header;
