// front_end-frameworks/svelte/src/App.svelte
<script>
    import Header from "./components/layout/Header.svelte";
    import Hero from "./components/sections/Hero.svelte";
    import About from "./components/sections/About.svelte";
    import Features from "./components/sections/Features.svelte";
    import Insights from "./components/sections/Insights.svelte";
    import Contact from "./components/sections/Contact.svelte";
    import Footer from "./components/layout/Footer.svelte";
</script>

<Header />

<main>
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
</main>

<Footer />

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from "./components/layout/Header.vue";
import Footer from "./components/layout/Footer.vue";
import Hero from "./sections/Hero.vue";
import About from "./sections/About.vue";
import Features from "./sections/Features.vue";
import Insights from "./sections/Insights.vue";
import Contact from "./sections/Contact.vue";
</script>

<template>
    <Header />

    <main>
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
    </main>

    <Footer />
</template>
