// front_end-frameworks/vue/src/sections/Insights.vue
<script setup>
import { onMounted, ref } from "vue";
import InsightCard from "../components/cards/InsightCard.vue";
import SectionBadge from "../components/ui/SectionBadge.vue";
import SectionTitle from "../components/ui/SectionTitle.vue";
import { getInsights } from "../services/insightsServices.js";

const insights = ref([]);
const error = ref("");

onMounted(async () => {
    try {
        error.value = "";
        insights.value = await getInsights();
    } catch {
        error.value = "Unable to load insights.";
    }
});
</script>

<template>
  <section
    id="insights-section"
    class="bg-slate-950"
  >
    <div class="mx-auto flex max-w-6xl flex-col items-center px-6 py-24 text-center">
      <SectionBadge
        text="Insights"
        class="mb-4"
      />
      <SectionTitle
        title="Explore Agentic AI"
        highlight="Through real-world scenes"
      />
      <div
        class="mt-6 min-h-6"
        aria-live="polite"
      >
        <p
          v-if="error"
          role="alert"
          class="text-sm text-red-400"
        >
          {{ error }}
        </p>
      </div>
      <div class="mt-6 grid w-full gap-8 md:grid-cols-2 lg:grid-cols-3">
        <InsightCard
          v-for="(insight, index) in insights"
          :key="insight.title"
          :category="insight.category"
          :title="insight.title"
          :description="insight.description"
          :image="insight.image"
          :index="index"
        />
      </div>
    </div>
  </section>
</template>

// front_end-frameworks/react/src/sections/Insights.jsx
import { useEffect, useState } from "react";
import { Astroid } from "lucide-react";
import InsightCard from "../components/InsightCard.jsx";
import { getInsights } from "../services/insightsService.js";


function Insights() {
    const [insights, setInsights] = useState([]);
    const [error, setError] = useState("");

    useEffect(() => {
        const loadInsights = async () => {
            try {
                setError("");

                const data = await getInsights();

                setInsights(data);
            } catch {
                setError("Unable to load insights.");
            }
        };

        loadInsights();
    }, []);

    return (

        
        <section
            id="insights-section"
            className="max-w-6xl mx-auto px-6 flex min-h-screen flex-col items-center justify-center py-24 text-center"
        >
            <p className="inline-flex items-center gap-1 mb-4 rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300">
                    <Astroid color="#C4B5FD" fill="#C4B5FD" size={8} />

                    Insights

                    <Astroid color="#C4B5FD" fill="#C4B5FD" size={8} />
            </p>

            <h2 className="text-4xl font-black leading-none tracking-tight md:text-5xl">
                <span className="text-slate-50">
                    Explore Agentic AI
                </span>

                <span className="block text-violet-300">
                    Through real-world scenes
                </span>
            </h2>



            <div
                className="mt-6 min-h-6"
                aria-live="polite"
            >
                {error && (
                    <p
                        role="alert"
                        className="text-sm text-red-400"
                    >
                        {error}
                    </p>
                )}
            </div>

            <div className="mt-6 grid w-full gap-8 md:grid-cols-2">
                {insights.map((insight, index) => (
                    <InsightCard
                        key={insight.title}
                        category={insight.category}
                        title={insight.title}
                        description={insight.description}
                        image={insight.image}
                        index={index}
                    />
                ))}
            </div>
        </section>
    );
}


export default Insights;
